
-- =============================================================
-- ACTIVIDAD: CASO 1
-- BLOQUE ADMIN (ejecutar como ADMIN)
-- ============================

SET SERVEROUTPUT ON

DROP USER PRY2205_USER1 CASCADE;
DROP USER PRY2205_USER2 CASCADE;

CREATE USER
    PRY2205_USER1 IDENTIFIED BY "Actividad.USER1_S8"
    DEFAULT TABLESPACE DATA
    TEMPORARY TABLESPACE TEMP;

CREATE USER
    PRY2205_USER2 IDENTIFIED BY "Actividad.USER2_S8"
    DEFAULT TABLESPACE DATA
    TEMPORARY TABLESPACE TEMP;

  -- Asignar cuotas
ALTER USER PRY2205_USER1 DEFAULT TABLESPACE DATA;
ALTER USER PRY2205_USER1 QUOTA UNLIMITED ON DATA; 
ALTER USER PRY2205_USER1 TEMPORARY TABLESPACE TEMP;
ALTER USER PRY2205_USER2 QUOTA UNLIMITED ON DATA;

  -- Drops
DROP ROLE PRY2205_ROL_D; 
DROP ROLE PRY2205_ROL_P;
-- Creacion de Roles
CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_P;


-- Otorgar privilegios de sistema requeridos directamente al USER1)
GRANT CREATE TABLE TO PRY2205_USER1;
GRANT CREATE VIEW TO PRY2205_USER1;
GRANT CREATE TYPE TO PRY2205_USER1;
GRANT CREATE SEQUENCE TO PRY2205_USER1;
GRANT CREATE TRIGGER TO PRY2205_USER1;
GRANT CREATE SYNONYM TO PRY2205_USER1;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_USER1;
GRANT DROP PUBLIC SYNONYM TO PRY2205_USER1;
GRANT CREATE PROCEDURE TO PRY2205_USER1;
GRANT DROP ANY TABLE TO PRY2205_USER1;

-- Otorgar privilegios de sistema a los roles
GRANT CREATE SESSION TO PRY2205_ROL_D;
GRANT CREATE SYNONYM TO PRY2205_ROL_D;
GRANT CREATE SESSION TO PRY2205_ROL_P;
GRANT CREATE SEQUENCE TO PRY2205_ROL_P;
GRANT CREATE TRIGGER TO PRY2205_ROL_P;
GRANT CREATE TABLE TO PRY2205_ROL_P;

--===============================================================
-- EJECUTAR ESQUEMA POBLADO QUE ENVÍO ANTES DE OTORGAR LOS SELECT
--===============================================================


-- Otorgar SELECT directo a USER2
GRANT SELECT ON PRY2205_USER1.LIBRO    TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.EJEMPLAR TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.PRESTAMO TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.ALUMNO   TO PRY2205_USER2;

-- Permitir que USER2 pueda ejecutar CTAS
GRANT CREATE TABLE TO PRY2205_USER2;
GRANT DROP ANY TABLE TO PRY2205_USER2;

-- Asignar cuota de tablespace
ALTER USER PRY2205_USER2 QUOTA UNLIMITED ON DATA;

GRANT PRY2205_ROL_D TO PRY2205_USER1;
GRANT PRY2205_ROL_P TO PRY2205_USER2;





-- =============================================================
-- CASO 2: CREACIÓN DE INFORME CONTROL_STOCK_LIBROS
-- Ejecutar como PRY2205_USER2
-- =============================================================

SET SERVEROUTPUT ON SIZE 200000

-- Limpiar objetos previos
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CONTROL_STOCK_LIBROS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONTROL_STOCK';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CTRLSTK_BI';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX IDX_CTRLSTK_LIBROID';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX IDX_CTRLSTK_STOCK_CRITICO';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX IDX_CTRLSTK_PORCENTAJE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

DROP TABLE CONTROL_STOCK_LIBROS;

CREATE TABLE CONTROL_STOCK_LIBROS AS
SELECT
  ROW_NUMBER() OVER (ORDER BY l.libroid) AS ID_CONTROL,
  l.libroid AS LIBRO_ID,
  l.nombre_libro AS NOMBRE_LIBRO,
  NVL(ej.TOTAL_EJEMPLARES, 0) AS TOTAL_EJEMPLARES,
  NVL(pagg.EN_PRESTAMO, 0) AS EN_PRESTAMO,
  NVL(ej.TOTAL_EJEMPLARES, 0) - NVL(pagg.EN_PRESTAMO, 0) AS DISPONIBLES,
  ROUND(
    CASE
      WHEN NVL(ej.TOTAL_EJEMPLARES, 0) = 0 THEN 0
      ELSE (NVL(pagg.EN_PRESTAMO, 0) / NVL(ej.TOTAL_EJEMPLARES, 0)) * 100
    END, 0) AS PORCENTAJE_PRESTAMO,
  CASE
    WHEN (NVL(ej.TOTAL_EJEMPLARES, 0) - NVL(pagg.EN_PRESTAMO, 0)) > 2 THEN 'S'
    ELSE 'N'
  END AS STOCK_CRITICO,
  -- Mes y año del proceso
  TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'MM'), -24),'MM') AS MES_PROCESO,
  TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'MM'), -24),'YYYY') AS ANIO_PROCESO
FROM syn_libro l
LEFT JOIN (
  SELECT libroid, COUNT(*) AS TOTAL_EJEMPLARES
  FROM syn_ejemplar
  GROUP BY libroid
) ej ON ej.libroid = l.libroid
LEFT JOIN (
  -- EN_PRESTAMO: número de préstamos registrados en el mes procesado por empleados 150,180,190
  SELECT libroid, COUNT(*) AS EN_PRESTAMO
  FROM syn_prestamo
  WHERE empleadoid IN (150, 180, 190)
    AND fecha_inicio BETWEEN
      ADD_MONTHS(TRUNC(SYSDATE,'MM'), -24)
      AND LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE,'MM'), -24))
  GROUP BY libroid
) pagg ON pagg.libroid = l.libroid
ORDER BY l.libroid
;

-- Agregar constraints
ALTER TABLE CONTROL_STOCK_LIBROS ADD CONSTRAINT PK_CONTROL_STOCK PRIMARY KEY (ID_CONTROL);
ALTER TABLE CONTROL_STOCK_LIBROS ADD CONSTRAINT CHK_DISPONIBLES_POS CHECK (DISPONIBLES >= 0);

-- Crear secuencia
DECLARE
  v_max NUMBER;
BEGIN
  SELECT NVL(MAX(ID_CONTROL), 0) INTO v_max FROM CONTROL_STOCK_LIBROS;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_CONTROL_STOCK START WITH ' || TO_CHAR(v_max + 1) || ' INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
  NULL;
END;
/

-- Trigger para asignar ID_CONTROL usando la secuencia en INSERT posteriores
CREATE OR REPLACE TRIGGER TRG_CTRLSTK_BI
BEFORE INSERT ON CONTROL_STOCK_LIBROS
FOR EACH ROW
BEGIN
  IF :NEW.ID_CONTROL IS NULL THEN
    SELECT SEQ_CONTROL_STOCK.NEXTVAL INTO :NEW.ID_CONTROL FROM DUAL;
  END IF;
END;
/

-- Índices para optimizar consultas
CREATE INDEX IDX_CTRLSTK_LIBROID ON CONTROL_STOCK_LIBROS(LIBRO_ID);
CREATE INDEX IDX_CTRLSTK_STOCK_CRITICO ON CONTROL_STOCK_LIBROS(STOCK_CRITICO);
CREATE INDEX IDX_CTRLSTK_PORCENTAJE ON CONTROL_STOCK_LIBROS(PORCENTAJE_PRESTAMO DESC);

-- Permisos: USER1 Y 2 pueden leer el informe
GRANT SELECT ON CONTROL_STOCK_LIBROS TO PRY2205_ROL_P;
GRANT SELECT ON CONTROL_STOCK_LIBROS TO PRY2205_USER1;

-- Consulta final para ver resultados (orden por LIBRO_ID)
SELECT 
  ID_CONTROL,
  LIBRO_ID,
  NOMBRE_LIBRO,
  TOTAL_EJEMPLARES,
  EN_PRESTAMO,
  DISPONIBLES,
  PORCENTAJE_PRESTAMO,
  STOCK_CRITICO
FROM CONTROL_STOCK_LIBROS
ORDER BY LIBRO_ID;


-- ===============================================================
-- CASO 3: VW_DETALLE_MULTAS + índices de optimización
-- Ejecutar como: PRY2205_USER1
-- ===============================================================
SET SERVEROUTPUT ON SIZE 200000;

-- =========================
-- Limpieza
-- =========================
BEGIN
  BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_DETALLE_MULTAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  -- No dropeamos MULTA_REBAJA porque la usamos y ya fue creada en pasos previos
  BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_PRESTAMO_FECHA_TERMINO'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_PRESTAMO_FECHA_ENTREGA'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_PRESTAMO_ALUMNOID'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_PRESTAMO_LIBROID'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_ALUMNO_CARRERAID'; EXCEPTION WHEN OTHERS THEN NULL; END;
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Advertencia limpieza inicial: '||SQLERRM);
END;
/


-- =========================
-- Crear índices para optimizar la vista
-- Ejecutar como PRY2205_USER1
-- =========================
BEGIN
  BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_PRESTAMO_FECHA_TERMINO ON PRESTAMO(FECHA_TERMINO)'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_PRESTAMO_FECHA_ENTREGA ON PRESTAMO(FECHA_ENTREGA)'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_PRESTAMO_ALUMNOID ON PRESTAMO(ALUMNOID)'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_PRESTAMO_LIBROID ON PRESTAMO(LIBROID)'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_ALUMNO_CARRERAID ON ALUMNO(CARRERAID)'; EXCEPTION WHEN OTHERS THEN NULL; END;
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Advertencia creando índices: '||SQLERRM);
END;
/

-- =========================
-- Grants: permitir lectura de la vista a roles/usuarios necesarios
-- =========================
BEGIN
  BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON VW_DETALLE_MULTAS TO PRY2205_ROL_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON VW_DETALLE_MULTAS TO PRY2205_USER1'; EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/


CREATE OR REPLACE VIEW VW_DETALLE_MULTAS AS
SELECT
  p.prestamoid                                                   AS ID_PRESTAMO,

  RTRIM(
    NVL(a.nombre,'') || ' ' ||
    NVL(a.apaterno,'') || ' ' ||
    NVL(a.amaterno,'')
  )                                                              AS NOMBRE_ALUMNO,

  -- Nombre de la carrera
  NVL(c.descripcion, 'SIN CARRERA')                              AS NOMBRE_CARRERA,

  l.libroid                                                      AS ID_LIBRO,

  ROUND(NVL(l.precio,0), 0)                                      AS VALOR_LIBRO,

  TRUNC(p.fecha_termino)                                         AS FECHA_TERMINO,
  TRUNC(p.fecha_entrega)                                         AS FECHA_ENTREGA,

  (TRUNC(p.fecha_entrega) - TRUNC(p.fecha_termino))              AS DIAS_ATRASO,

  -- Multa: 3% del precio por día de atraso (entero)
  ROUND(
    NVL(l.precio,0) * 0.03 *
    (TRUNC(p.fecha_entrega) - TRUNC(p.fecha_termino)),
    0
  )                                                              AS VALOR_MULTA,

  NVL(mr.porc_rebaja_multa, 0)                                   AS PORCENTAJE_REBAJA_MULTA,

  -- Valor rebajado (entero)
  ROUND(
    ( NVL(l.precio,0) * 0.03 *
      (TRUNC(p.fecha_entrega) - TRUNC(p.fecha_termino))
    ) * NVL(mr.porc_rebaja_multa,0) / 100,
    0
  )                                                              AS VALOR_REBAJADO,

  -- Valor final a pagar (entero)
  ROUND(
    ( NVL(l.precio,0) * 0.03 *
      (TRUNC(p.fecha_entrega) - TRUNC(p.fecha_termino))
    ) * (1 - NVL(mr.porc_rebaja_multa,0) / 100),
    0
  )                                                              AS VALOR_A_PAGAR

FROM SYN_PRESTAMO p
JOIN SYN_ALUMNO   a ON p.alumnoid = a.alumnoid
JOIN SYN_LIBRO    l ON p.libroid  = l.libroid
LEFT JOIN CARRERA c ON a.carreraid = c.carreraid
LEFT JOIN MULTA_REBAJA mr ON a.carreraid = mr.carreraid

WHERE
  EXTRACT(YEAR FROM p.fecha_termino) =
  EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -24))
  AND p.fecha_termino < p.fecha_entrega;


SELECT
  ID_PRESTAMO,
  NOMBRE_ALUMNO,
  NOMBRE_CARRERA,
  ID_LIBRO,
  VALOR_LIBRO,
  FECHA_TERMINO,
  FECHA_ENTREGA,
  DIAS_ATRASO,
  VALOR_MULTA,
  PORCENTAJE_REBAJA_MULTA,
  VALOR_REBAJADO,
  VALOR_A_PAGAR
FROM VW_DETALLE_MULTAS
ORDER BY FECHA_ENTREGA DESC
FETCH FIRST 20 ROWS ONLY;

CREATE INDEX IDX_PRESTAMO_YEAR_FT
ON PRESTAMO ( EXTRACT(YEAR FROM FECHA_TERMINO) );

EXPLAIN PLAN FOR
SELECT *
FROM VW_DETALLE_MULTAS;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
